name: Run Script Every 6 Hours FR

on:
  schedule:
    - cron: '0 */3 * * *'  # Run every 3 hours
  workflow_dispatch:      # Enable manual triggering

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Create fr and ar Folders
        run: |
          mkdir -p fr
          mkdir -p ar

      # ------------------------
      # Generate M3U8 files
      # ------------------------
      - name: Generate M3U8 Files
        run: |
          set -e  # Stop on errors

          generate_m3u8() {
            local url=$1
            local output=$2
            echo "Processing $output from $url ..."
            link=$(curl -k -s -H "User-Agent: Mozilla/5.0" "$url" | grep -oP "source:\s*'\K[^']+(?=',)")
            if [[ -n "$link" ]]; then
              content=$(curl -k -s -e "https://callofliberty.fr/" -H "Origin: https://callofliberty.fr" -A "Mozilla/5.0" "$link")
              if [[ -n "$content" ]]; then
                echo "$content" > "$output"
                echo "Created $output"
              else
                echo "Warning: No content found for $output"
              fi
            else
              echo "Warning: No source link found for $output"
            fi
          }

          # TF1 Channels
          generate_m3u8 "https://callofliberty.fr/tv/1-TF1/1-TF1.php" "fr/videotf1.m3u8"
          generate_m3u8 "https://callofliberty.fr/tv/20-TF1SERIESFILMS/20-TF1SERIESFILMS.php" "fr/videotf1fs.m3u8"
          generate_m3u8 "https://callofliberty.fr/tv/1-TF1/1-TF1.php" "fr/videotmc.m3u8"  # using sed TF1->TMC
          sed -i 's|TF1|TMC|g' fr/videotmc.m3u8
          generate_m3u8 "https://callofliberty.fr/tv/11-TFX/11-TFX.php" "fr/videotfx.m3u8"
          generate_m3u8 "https://callofliberty.fr/tv/76-CANALPLUS/76-CANALPLUS.php" "fr/videocp.m3u8"
          generate_m3u8 "https://callofliberty.fr/tv/9-W9/9-W9.php" "fr/videow9.m3u8"
          generate_m3u8 "https://callofliberty.fr/tv/22-6ter/22-6ter.php" "fr/video6ter.m3u8"

      # ------------------------
      # Commit and Push
      # ------------------------
      - name: Commit and Push Changes
        env:
          TEE_TV_APP: ${{ secrets.TEE_TV_APP }}
        run: |
          git config --local user.email "kada.developers@gmail.com"
          git config --local user.name "kadadevelopers"
          git add fr/*.m3u8 ar/*.m3u || echo "No new files to add"
          git diff-index --quiet HEAD || git commit -m "latest updates"
          git push "https://$TEE_TV_APP@github.com/kadadevelopers/live-m3u8.git"
